const { createClient } = require('@supabase/supabase-js');
require('dotenv').config();

const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY);
const ADMIN_CHAT_ID = process.env.TELEGRAM_CHAT_ID;
const TELEGRAM_BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN;

const MONTH_NAMES = ['January','February','March','April','May','June',
                     'July','August','September','October','November','December'];

async function sendTelegramMessage(text) {
    const url = `https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage`;
    const res = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ chat_id: ADMIN_CHAT_ID, text, parse_mode: 'Markdown' })
    });
    const data = await res.json();
    if (!data.ok) throw new Error(`Telegram error: ${data.description}`);
}

async function buildMonthlyReport() {
    const now = new Date();
    const year = now.getFullYear();
    const month = now.getMonth();

    const startDate = new Date(year, month, 1).toISOString();
    const endDate   = new Date(year, month + 1, 0, 23, 59, 59).toISOString();

    const { data: orders, error } = await supabase
        .from('orders')
        .select('id, total, items, status, created_at')
        .in('status', ['Paid', 'Collected'])
        .gte('created_at', startDate)
        .lte('created_at', endDate);

    if (error) {
        console.error('Supabase error:', error.message);
        return `❌ Error fetching data: ${error.message}`;
    }

    if (!orders || orders.length === 0) {
        return `📊 *Monthly Report — ${MONTH_NAMES[month]} ${year}*\n\nNo completed orders this month.`;
    }

    const totalIncome = orders.reduce((sum, o) => {
        const val = typeof o.total === 'string'
            ? parseFloat(o.total.replace(/[^\d.]/g, ''))
            : Number(o.total) || 0;
        return sum + val;
    }, 0);

    const totalOrders = orders.length;

    const itemCount = {};
    for (const order of orders) {
        const items = Array.isArray(order.items) ? order.items : JSON.parse(order.items || '[]');
        for (const item of items) {
            const name = item.name || 'Unknown';
            const qty  = item.qty || item.quantity || 1;
            itemCount[name] = (itemCount[name] || 0) + qty;
        }
    }

    const sorted = Object.entries(itemCount).sort((a, b) => b[1] - a[1]);

    const topItems = sorted.slice(0, 3)
        .map((e, i) => `  ${['🥇','🥈','🥉'][i]} ${e[0]} — ${e[1]} sold`)
        .join('\n');

    const lowest = sorted[sorted.length - 1];
    const lowestLine = lowest ? `  📉 ${lowest[0]} — ${lowest[1]} sold` : '  N/A';

    return `
📊 *Monthly Report — ${MONTH_NAMES[month]} ${year}*
━━━━━━━━━━━━━━━━━━━━
💰 *Total Income:* ₹${totalIncome.toFixed(2)}
🧾 *Total Orders:* ${totalOrders}

🏆 *Top Selling Items:*
${topItems}

📉 *Lowest Selling Item:*
${lowestLine}
━━━━━━━━━━━━━━━━━━━━
_Auto-generated by CanteenGo_ 🍽️
    `.trim();
}

async function main() {
    console.log('🚀 Running monthly report...');
    const report = await buildMonthlyReport();
    await sendTelegramMessage(report);
    console.log('✅ Monthly Telegram report sent.');
}

main().catch(err => {
    console.error('❌ Failed:', err.message);
    process.exit(1);
});