const TelegramBot = require('node-telegram-bot-api');
const cron = require('node-cron');
const { createClient } = require('@supabase/supabase-js');
require('dotenv').config();
// Enable polling so the bot can receive messages from users
const bot = new TelegramBot(process.env.TELEGRAM_BOT_TOKEN, {
    webHook: {
        port: process.env.PORT || 3000
    }
});
bot.setWebHook(`${process.env.RENDER_URL}/bot${process.env.TELEGRAM_BOT_TOKEN}`);
const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY);
const ADMIN_CHAT_ID = process.env.TELEGRAM_CHAT_ID;

const MONTH_NAMES = ['January','February','March','April','May','June',
                     'July','August','September','October','November','December'];

async function buildMonthlyReport() {
    const now = new Date();
    const year = now.getFullYear();
    const month = now.getMonth();

    const startDate = new Date(year, month, 1).toISOString();
    const endDate   = new Date(year, month + 1, 0, 23, 59, 59).toISOString();

    // Fetch all Paid + Collected orders this month
    const { data: orders, error } = await supabase
        .from('orders')
        .select('id, total, items, status, created_at')
        .in('status', ['Paid', 'Collected'])
        .gte('created_at', startDate)
        .lte('created_at', endDate);

    if (error) {
        console.error('Supabase error:', error.message);
        return `❌ Error fetching data: ${error.message}`;
    }

    if (!orders || orders.length === 0) {
        return `📊 *Monthly Report — ${MONTH_NAMES[month]} ${year}*\n\nNo completed orders this month.`;
    }

    // Total income
    const totalIncome = orders.reduce((sum, o) => {
        const val = typeof o.total === 'string'
            ? parseFloat(o.total.replace(/[^\d.]/g, ''))
            : Number(o.total) || 0;
        return sum + val;
    }, 0);

    const totalOrders = orders.length;

    // Count item frequencies
    const itemCount = {};
    for (const order of orders) {
        const items = Array.isArray(order.items) ? order.items : JSON.parse(order.items || '[]');
        for (const item of items) {
            const name = item.name || 'Unknown';
            const qty  = item.qty || item.quantity || 1;
            itemCount[name] = (itemCount[name] || 0) + qty;
        }
    }

    const sorted = Object.entries(itemCount).sort((a, b) => b[1] - a[1]);

    const topItems = sorted.slice(0, 3)
        .map((e, i) => `  ${['🥇','🥈','🥉'][i]} ${e[0]} — ${e[1]} sold`)
        .join('\n');

    const lowest = sorted[sorted.length - 1];
    const lowestLine = lowest ? `  📉 ${lowest[0]} — ${lowest[1]} sold` : '  N/A';

    const message = `
📊 *Monthly Report — ${MONTH_NAMES[month]} ${year}*
━━━━━━━━━━━━━━━━━━━━
💰 *Total Income:* ₹${totalIncome.toFixed(2)}
🧾 *Total Orders:* ${totalOrders}

🏆 *Top Selling Items:*
${topItems}

📉 *Lowest Selling Item:*
${lowestLine}
━━━━━━━━━━━━━━━━━━━━
_Auto-generated by CanteenGo_ 🍽️
    `.trim();

    return message;
}

// Send report to the admin chat (used by cron)
async function sendMonthlyReport() {
    const report = await buildMonthlyReport();
    await bot.sendMessage(ADMIN_CHAT_ID, report, { parse_mode: 'Markdown' });
    console.log('✅ Monthly Telegram report sent.');
}

// ─── Listen for "hi" messages and reply with the current month's summary ───
bot.on('message', async (msg) => {
    const chatId = msg.chat.id;
    const text = (msg.text || '').trim().toLowerCase();

    if (text === 'hi' || text === 'hello' || text === 'hey') {
        console.log(`📩 Received "${msg.text}" from chat ${chatId}`);
        await bot.sendMessage(chatId, '⏳ Generating your monthly summary...');

        try {
            const report = await buildMonthlyReport();
            await bot.sendMessage(chatId, report, { parse_mode: 'Markdown' });
        } catch (err) {
            console.error('Error generating report:', err);
            await bot.sendMessage(chatId, '❌ Sorry, something went wrong generating the report.');
        }
    }
});

// ─── Auto-send at end of every month (11:59 PM on last day) ───
cron.schedule('59 23 28-31 * *', () => {
    const today = new Date();
    const tomorrow = new Date(today);
    tomorrow.setDate(today.getDate() + 1);
    if (tomorrow.getDate() === 1) {
        sendMonthlyReport();
    }
});

console.log('🤖 Telegram bot is running — listening for messages & scheduled reports.');

module.exports = { sendMonthlyReport, buildMonthlyReport };